name = "CaoHamilton2008"
version = "0.1.2"

# ├── differential_geometry/         
# │   ├── lakefile.toml
# │   └── DifferentialGeometry.lean
# └── differential_geometry-papers/  
#     ├── lakefile.toml              
#     ├── lean-toolchain             
#     └── CaoHamilton2008/           
#         └── CaoHamilton2008.lean
[[require]]
name = "differential_geometry"
path = "../../differential-geometry"

[[lean_lib]]
name = "CaoHamilton2008"
